title: 'Plateforme MTA'
default_lang: fr
author:
  name: 'Plateforme MTA'
  email: contact@plateforme-mta.com
taxonomies:
  - category
  - tag
metadata:
  description: 'MTA plateforme d’essais propose depuis plus de 10 ans des prestations pour les professionnels. MTA vous accompagne pour vos essais de batteries et autres projets de développement de systèmes de stockage.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
