title: 'Plateforme MTA'
default_lang: fr
author:
  name: 'Plateforme MTA'
  email: contact@plateforme-mta.com
taxonomies:
  - category
  - tag
metadata:
  description: 'MTA Plateforme d’Essais encadre des projets R&D sur les véhicules hybrides et électriques, Batteries, Supercondensateur, Li-ion, Ni-MH, GMP électrique...'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
